package com.acme;

import com.acme.statusmgr.beans.BaseServerStatus;
import com.acme.statusmgr.facade.RealSystemInfo;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


/**
 * Standard main class for Spring, generated by Spring template
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        BaseServerStatus.setProvider(new RealSystemInfo());
        SpringApplication.run(Application.class, args);
    }
}
